nodejs:
  applicationPort: 4000
  aadIdentityName: lau
  ingressHost: lau-case-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/lau/case-frontend:latest'
  environment:
    USE_REDIS: true
    REDIS_USE_TLS: true
    REDIS_PORT: 6380
    REDIS_HOST: lau-case-frontend-redis-cache-{{ .Values.global.environment }}.redis.cache.windows.net

  keyVaults:
    lau:
      resourceGroup: lau
      secrets:
      # - AppInsightsInstrumentationKey
        - case-frontend-redis-access-key

redis:
  architecture: standalone
  replica:
    replicaCount: 0
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  enabled: false
