nodejs:
  applicationPort: 4000
  aadIdentityName: lau
  ingressHost: lau-case-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/lau/case-frontend:latest'
  environment:
    USE_REDIS: true
    REDIS_USE_TLS: true
    REDIS_PORT: 6380
    REDIS_HOST: lau-case-frontend-session-storage-{{ .Values.global.environment }}.redis.cache.windows.net
    IDAM_WEB_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token"
    OAUTH_CLIENT_REDIRECT: "https://lau-case.{{ .Values.global.environment }}.platform.hmcts.net/oauth2/callback"


  keyVaults:
    lau:
      resourceGroup: lau
      secrets:
        - AppInsightsInstrumentationKey
        - case-frontend-redis-access-key
        - idam-client-secret

redis:
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
  enabled: false

idam-pr:
  enabled: false
