---
service:
  name: 'lau-case-frontend'
environment: 'prod'
useCSRFProtection: true
security:
  referrerPolicy: origin
appInsights:
  instrumentationKey: false
redis:
  host: 'localhost'
  port: 6379
  password: 'dummy_password'
  useTLS: 'false'
  enabled: false
  secret: 'OVERWRITE_THIS'
  proxy: true
  resave: false
  saveUninitialized: false
  cookie:
    secure: false
    httpOnly: true
    sameSite: 'lax'
services:
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    clientID: 'lau'
    clientSecret: 'SECRET'
    callbackURL: 'http://localhost:3001/oauth2/callback'
